{
  "type": "record",
  "name": "CreatorValue",
  "namespace": "com.hiberus.creatorsProducer.avro",
  "fields": [{
    "name": "name",
    "type": ["null", "string"],
    "default": null,
    "doc": "Name of creator"
  }, {
    "name": "surname",
    "type": ["null", "string"],
    "default": null,
    "doc": "Surname of creator"
  }, {
    "name": "birth",
    "type": ["null", {
      "type": "int",
      "logicalType": "date"
    }],
    "default": null,
    "doc": "Date of birth of creator"
  }, {
    "name": "email",
    "type": ["null", "string"],
    "default": null,
    "doc": "Email of creator"
  }, {
    "name": "phone",
    "type": ["null", "string"],
    "default": null,
    "doc": "Phone of creator"
  }]
}